### PR TITLE
Adding endpoint config to `NotDiamond` [ENG-965].

### PR DESCRIPTION
**Pull request by acompa**
Users should have the ability to configure a target API endpoint if they so desire. This will be useful for local deployments, as well as proxy-hosted capabilities.

### CODE REVIEW

**Review by r0ymanesco — COMMENTED** [review]
I think you need to do it for the `.invoke` methods as well

**Review by r0ymanesco — APPROVED** [review]
Approving but please remove the perplexity 32k test since that model is deprecated

**Comment by acompa** [comment]
> Approving but please remove the perplexity 32k test since that model is deprecated

Yep it's already been renamed - the underlying test used the new Llama 3.1 model.

**Comment by acompa** [comment]
Failed on Replicate, should be fine.

**Pull request merged**
